// THROWAWAY UI PROTOTYPE. Three growth-home layouts on /?variant=A|B|C.
// All domain fixtures come from mock-data.json. Nothing is sent to a backend.

const paths = {
  arrow:'M5 12h14m-5-5 5 5-5 5', back:'m14 6-6 6 6 6', chevron:'m9 6 6 6-6 6', close:'m6 6 12 12M18 6 6 18',
  check:'m5 12 4 4L19 6', circle:'M20 12a8 8 0 1 1-16 0 8 8 0 0 1 16 0', retry:'M4 10a8 8 0 1 1 1 8M4 4v6h6',
  sprout:'M12 21v-9M12 15C3 16 3 7 3 7s9-1 9 8m0-5C11 2 21 3 21 3s0 9-9 9',
  tree:'M12 22v-5M7 17a4 4 0 0 1-3-7 4 4 0 0 1 4-6 4 4 0 0 1 8 0 4 4 0 0 1 4 6 4 4 0 0 1-3 7Z',
  book:'M3 4h6q3 0 3 3v14q0-3-3-3H3Zm18 0h-6q-3 0-3 3v14q0-3 3-3h6Z',
  target:'M21 12a9 9 0 1 1-9-9m5 9a5 5 0 1 1-5-5m0 5 9-9m-5 0h5v5',
  person:'M16 6a4 4 0 1 1-8 0 4 4 0 0 1 8 0M4 22v-3a8 8 0 0 1 16 0v3',
  people:'M14 7a3 3 0 1 1-6 0 3 3 0 0 1 6 0M4 21v-2a7 7 0 0 1 14 0v2M18 4a3 3 0 0 1 0 6m2 4q3 1 3 5',
  home:'m3 10 9-7 9 7v10H3Zm6 10v-6h6v6', card:'M3 4h18v16H3Zm0 5h18M6 16h4',
  wallet:'M3 6h18v15H3Zm1 0V3h14v3m-2 5h6v5h-6Z',cash:'M2 6h20v13H2ZM15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0M5 12h1m12 0h1',
  chart:'m3 17 6-6 4 4 8-11M16 4h5v5M3 21h18', bag:'M4 7h16l-1 14H5Zm4 0V5a4 4 0 0 1 8 0v2',
  plane:'m2 13 8 1 3 7 2-1-1-7 6-5q3-3 1-5-2-2-5 1l-5 6-7-1Z',shield:'m12 2 9 4v6q-1 7-9 10-8-3-9-10V6Zm-4 9 3 3 5-6',
  building:'M3 21h18M5 21V9h14v12M3 9l9-6 9 6M9 12v6m6-6v6', transfer:'M3 7h17m-4-4 4 4-4 4M21 17H4m4-4-4 4 4 4',
  receipt:'M5 3h14v19l-3-2-4 2-4-2-3 2ZM8 8h8m-8 4h8m-8 4h4', qr:'M3 3h6v6H3Zm12 0h6v6h-6ZM3 15h6v6H3Zm12 0v3h3v3h3v-6h-3m-6-3h-1m-2 6h1',
  search:'M16 10a6 6 0 1 1-12 0 6 6 0 0 1 12 0m-2 4 7 7', bell:'M5 16h14l-2-4V8a5 5 0 0 0-10 0v4Zm4 4h6',
  star:'m12 2 3 6 7 1-5 5 1 7-6-3-6 3 1-7-5-5 7-1Z',spark:'m12 3 2 6 6 3-6 2-2 7-2-7-7-2 7-3Zm7-2 1 3 3 1-3 1-1 3-1-3-3-1 3-1Z',
  clock:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0m-9-5v6l4 2',calendar:'M3 5h18v16H3ZM3 10h18M7 2v6m10-6v6m-10 8h3',
  palette:'M12 3a9 9 0 1 0 0 18h2q3 0 1-3t2-3h1q3 0 3-3a9 9 0 0 0-9-9Zm-5 7h.01M10 7h.01m5 1h.01m3 4h.01',
  code:'m8 6-6 6 6 6m8-12 6 6-6 6m-3-14-2 16',jira:'m12 2 10 10-10 10L2 12Zm0 7-3 3 3 3 3-3Z',
  lock:'M5 10h14v12H5Zm3 0V6a4 4 0 0 1 8 0v4m-4 5v3',plus:'M12 4v16M4 12h16', info:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0m-9-1v6m0-10v1',
  award:'M18 8a6 6 0 1 1-12 0 6 6 0 0 1 12 0M8 13l-2 9 6-3 6 3-2-9',message:'M3 3h18v14H9l-6 4Zm4 5h10m-10 4h7',
  leaf:'M20 3Q2 1 3 14q1 7 8 6Q23 17 20 3ZM4 20 16 8',sun:'M16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0M12 1v3m0 16v3M1 12h3m16 0h3M4 4l2 2m12 12 2 2M4 20l2-2M18 6l2-2',
  moon:'M20 15A9 9 0 0 1 9 3 9 9 0 1 0 20 15', settings:'M9 3h6l1 3 3 1 2 5-2 5-3 1-1 3H9l-1-3-3-1-2-5 2-5 3-1Zm7 9a4 4 0 1 1-8 0 4 4 0 0 1 8 0',
  mail:'M3 5h18v15H3Zm0 0 9 8 9-8',logout:'M9 3H3v18h6m5-15 6 6-6 6m-6-6h12', coffee:'M3 7h13v11q-1 3-6 3t-7-3Zm13 1h2a4 4 0 0 1 0 8h-2M6 2v2m4-2v2', heart:'M12 21 3 12C-4 4 7-2 12 6 17-2 28 4 21 12Z',download:'M12 3v12m-5-5 5 5 5-5M4 17v4h16v-4'
};
const icon = (name, cls='') => `<svg class="icon ${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.leaf}"/></svg>`;
const halykIcon = `<svg class="halyk-symbol" viewBox="0 0 30 30" fill="none" aria-hidden="true"><path d="m15 2 5 3 5 1 1 6 2 3-3 5-1 5-6 1-3 2-5-3-5-1-1-6-2-3 3-5 1-5 6-1Z" stroke="currentColor" stroke-width="1.5"/><path d="M15 6a9 9 0 1 0 9 9 9 9 0 0 0-9-9Z" stroke="currentColor" stroke-width="1.4"/><path d="M10 18q4-1 4-6l6-2-2 6-8 5Z" fill="currentColor"/></svg>`;
const esc = value => String(value??'').replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt = value => new Intl.NumberFormat('ru-RU').format(value);
const clone = value => structuredClone(value);
const data = await fetch('./mock-data.json').then(r=>{if(!r.ok)throw new Error('mock-data.json unavailable');return r.json()});
const app = document.querySelector('#app');
const modalRoot = document.querySelector('#modal-root');
const qs = new URLSearchParams(location.search);
let variant = data.variants.some(v=>v.id===qs.get('variant')) ? qs.get('variant') : 'A';
let state;
let modalReturnFocus;
let toastTimer;
let modalType = null;
const statusName = {passed:'Пройдено',new:'Не начато',failed:'Повторить'};
function reset(employeeId='aizhan', view='bank') {
  const employee = clone(data.employees.find(e=>e.id===employeeId)||data.employees[0]);
  state = {employee, isEmployee:employeeId!=='guest', view, tests:clone(data.tests), plan:[], goalId:employee.goalId, xp:employee.xp, tree:employee.tree, theme:employee.theme, testTab:'required', filter:'all', category:'Все', search:'', quiz:null, result:null, attempts:[], contributions:clone(data.contributions), earned:[...data.tests.filter(t=>t.status==='passed').map(t=>'test-'+t.id),...data.contributions.filter(c=>c.status==='confirmed').map(c=>c.id)], meetings:[], jiraConnected:true, jiraSynced:false, lastSync:data.jira.lastSync, draft:null};
  closeModal(false); render();
}
const currentLevel = () => data.levels.filter(l=>state.xp>=l.xp).at(-1);
const nextLevel = () => data.levels.find(l=>l.xp>state.xp);
const levelProgress = () => nextLevel()?Math.min(100,100*state.xp/nextLevel().xp):100;
const tenure = (months=state.employee.tenureMonths) => months===12?'1 год':months===24?'2 года':`${months} месяцев`;
const goal = () => data.goals.find(g=>g.id===state.goalId);
const test = id => state.tests.find(t=>t.id===id);
const countStatus = name => state.tests.filter(t=>t.required&&t.status===name).length;
const tree = (props={}) => {
  const {species=state.tree,theme=state.theme,months=state.employee.tenureMonths,miniature=false}=props;
  const speciesData=data.trees.find(t=>t.id===species);
  const size=months>=24?1:months>=12?.85:.65;
  return `<span class="tree-art generated-tree ${theme} ${miniature?'miniature':''}" style="--tree-scale:${size}"><img src="${speciesData.asset}" alt="${speciesData.name}, стаж ${months} месяцев" width="1024" height="1024" draggable="false">${theme==='night'?'<i class="firefly f1"></i><i class="firefly f2"></i><i class="firefly f3"></i>':''}</span>`;
};
const progress = (value) => `<div class="progress"><span style="width:${Math.max(0,Math.min(100,value))}%"></span></div>`;
const xp = value => `<span class="xp-pill">${icon('spark')}+${fmt(value)} XP</span>`;
const pill = (text,name='',type='')=>`<span class="pill ${type}">${name?icon(name):''}${text}</span>`;
function header(title,{back=null,sub='',action='notifications',actionIcon='bell'}={}) {
  return `<header class="app-header">${back?`<button class="icon-btn back-btn" data-action="navigate" data-view="${back}" aria-label="Назад">${icon('back')}</button>`:''}<div class="grow">${sub?`<div class="header-eyebrow">${sub}</div>`:''}<h2>${title}</h2></div><button class="icon-btn ${action==='notifications'?'notification-dot':''}" data-action="${action}" aria-label="${action==='notifications'?'Уведомления':'Настройки прототипа'}">${icon(actionIcon)}</button><button class="avatar" data-action="navigate" data-view="profile" aria-label="Профиль сотрудника">${state.employee.initials}</button></header>`;
}
function bottomNav() {
  if(state.view==='bank') return `<nav class="bottom-nav" aria-label="Навигация Halyk">${[['home','Главная'],['wallet','Мой банк'],['qr','QR'],['transfer','Переводы'],['receipt','Платежи']].map(([i,t],n)=>`<button class="nav-item ${n===0?'active':''} ${n===2?'qr':''}" data-action="bank-service" data-name="${t}" ${n===0?'aria-current="page"':''}>${icon(i)}<span>${t}</span></button>`).join('')}</nav>`;
  const active=['test','quiz','result'].includes(state.view)?'tests':['custom','activities'].includes(state.view)?'growth':state.view;
  return `<nav class="bottom-nav" aria-label="Навигация Мой рост">${[['growth','tree','Дерево'],['tests','book','Тесты'],['goals','target','Цели'],['profile','person','Профиль'],['bank',null,'Halyk']].map(([v,i,t])=>`<button class="nav-item ${active===v?'active':''} ${v==='bank'?'halyk-tab':''}" data-action="navigate" data-view="${v}" ${active===v?'aria-current="page"':''} aria-label="${v==='bank'?'Вернуться в Halyk':t}">${i?icon(i):halykIcon}<span>${t}</span></button>`).join('')}</nav>`;
}
function bankView() {
  return `<div class="bank-header"><button class="avatar" data-action="demo-profile" aria-label="Выбрать демо-профиль">${state.isEmployee?state.employee.initials:'Г'}</button><label class="search">${icon('search')}<input aria-label="Поиск сервисов Halyk" placeholder="Поиск" id="bank-search"></label><div class="bonus"><span>◉</span>${fmt(data.bank.cashback)}</div></div><main class="screen" id="screen">
    <section class="bank-banner">${pill('БЛИЖЕ К ВАМ')}<h3>Всё важное —<br>в Halyk</h3><p>Банк, покупки и возможности<br>в одном приложении.</p><div class="mini-bank-card">Halyk</div></section>
    <section class="bank-services" aria-label="Сервисы">${data.bank.services.map(s=>`<button class="bank-service" data-action="bank-service" data-name="${s.name}">${icon(s.icon)}<span>${s.name}</span></button>`).join('')}</section>
    ${state.isEmployee?`<section class="growth-entry" tabindex="0" role="button" data-action="navigate" data-view="growth" aria-label="Открыть Мой рост"><div class="eyebrow">СОТРУДНИКАМ HALYK</div><h3>Время расти.<br>В своём темпе.</h3><p>Ваши навыки, цели<br>и новые возможности.</p><span class="primary-btn">Мой рост ${icon('arrow')}</span>${tree()}</section>`:`<div class="card" style="margin-top:17px"><div class="eyebrow">ДОБРО ПОЖАЛОВАТЬ</div><h3 style="font-size:19px;margin-top:10px">Каждый день с Halyk</h3><p class="body-copy">Все ваши банковские сервисы — в одном месте.</p></div>`}
    <div class="section-heading"><h3>Все сервисы</h3><button class="text-btn" data-action="all-services">Смотреть ${icon('chevron')}</button></div><div class="services-more">${[['heart','Appteka'],['coffee','Рестораны'],['transfer','Halyk FX']].map(([i,t])=>`<button class="service-small" data-action="bank-service" data-name="${t}">${icon(i)}${t}</button>`).join('')}</div>
    ${state.isEmployee?`<p class="bank-greeting">${icon('shield')}Профиль сотрудника подтверждён</p>`:''}</main>`;
}
function treeHero() {
  return `<section class="tree-hero ${state.theme}"><div class="hero-top row between"><div><div class="hero-greeting">${state.employee.firstName}, это ваш маленький мир</div><h3>Расти в своём темпе</h3></div></div><div class="tree-stage">${tree()}<button class="tree-node sql" data-action="test-open" data-id="sql"><span class="node-circle">${icon('check')}</span>SQL</button><button class="tree-node ${test('react').status==='passed'?'':'new'} react" data-action="test-open" data-id="react"><span class="node-circle">${test('react').status==='passed'?icon('check'):''}</span>React</button><button class="tree-node ${test('architecture').status==='passed'?'':'failed'} architecture" data-action="test-open" data-id="architecture"><span class="node-circle">${icon(test('architecture').status==='passed'?'check':'retry')}</span>System Design</button></div><div class="hero-foot"><span>${tenure()} в Halyk · Уровень ${currentLevel().level}</span><button class="text-btn" data-action="navigate" data-view="custom">${icon('palette')}Настроить</button></div><div class="xp-line">${progress(levelProgress())}<span class="small">${fmt(state.xp)} / ${fmt(nextLevel()?.xp||state.xp)} XP</span></div></section>`;
}
function statuses() { return `<div class="status-grid">${['passed','new','failed'].map(s=>`<button class="status-tile ${s}" data-action="status-filter" data-filter="${s}"><span class="status-dot">${icon(s==='passed'?'check':s==='failed'?'retry':'circle')}</span><div><strong>${countStatus(s)}</strong><p>${statusName[s]}</p></div></button>`).join('')}</div>`; }
function goalReadiness(g=goal()) {
  const newlyConfirmed=g.steps.filter(s=>!s.done&&s.testId&&test(s.testId).status==='passed').length;
  return {count:g.confirmed+newlyConfirmed,percent:Math.round(100*(g.confirmed+newlyConfirmed)/g.total)};
}
function goalCard() {const g=goal(),r=goalReadiness();return `<button class="goal-card" data-action="navigate" data-view="goals"><span class="icon-tile">${icon('target')}</span><div class="grow"><div class="tiny muted">Моя карьерная цель</div><div class="goal-title">${g.shortTitle}</div>${progress(r.percent)}</div><span class="percent">${r.percent}<small style="font-size:10px">%</small></span>${icon('chevron')}</button>`;}
function nextTest(){return state.tests.find(t=>t.required&&t.status==='new')||state.tests.find(t=>t.required&&t.status==='failed')||state.tests.find(t=>!t.required&&t.status==='new');}
function nextCard(){const t=nextTest();return t?`<div class="section-heading"><h3>Следующий маленький шаг</h3><span class="tiny muted">ДЛЯ ВАС</span></div><section class="next-card"><div class="top"><span class="icon-tile">${icon('code')}</span><div><h3>${t.title}</h3><p>${t.required?'Для вашей роли':'Расширьте кругозор'} · ${t.minutes} минут</p></div></div><div class="bottom">${xp(t.xp)}<button class="primary-btn" data-action="test-open" data-id="${t.id}">Начать ${icon('arrow')}</button></div></section>`:`<div class="card"><h3>Все тесты пройдены!</h3><p class="body-copy">Обсудите следующий шаг с руководителем.</p></div>`;}
function activityLink(){return `<button class="activity-link" data-action="navigate" data-view="activities">${icon('spark')}Больше способов получить опыт${icon('chevron')}</button>`;}
function VariantA(){return `${treeHero()}${statuses()}${goalCard()}${nextCard()}${activityLink()}`;}
function VariantB(){const g=goal(),r=goalReadiness();return `<section class="journey-header"><div class="eyebrow">ВАША СЛЕДУЮЩАЯ ГЛАВА</div><h3>Сегодня Middle.<br>Завтра — больше.</h3><div class="row"><div><span class="pill">${g.title}</span><p class="small muted" style="margin-top:13px">${r.count} из ${g.total} навыков на пути к цели</p></div>${tree()}</div></section><div class="step-list journey-path">${g.steps.slice(0,4).map((step,i)=>stepRow(step,i)).join('')}</div><button class="primary-btn full" data-action="navigate" data-view="goals">Открыть карьерный маршрут ${icon('arrow')}</button>${statuses()}${activityLink()}`;}
function VariantC(){const t=nextTest();return `<section class="focus-intro"><div class="eyebrow">${state.employee.firstName.toUpperCase()}, СЕГОДНЯ ХОРОШИЙ ДЕНЬ</div><h3>Один шаг.<br>Новая возможность.</h3></section><section class="focus-main"><div class="row between"><div class="eyebrow">ФОКУС НА СЕГОДНЯ</div>${pill(`${t?.minutes||15} мин`,'clock','white')}</div><h3>${t?.title||'Обсудить рост'}</h3><p>${t?.description||'Обсудите ваш прогресс с руководителем.'}</p><button class="primary-btn" data-action="${t?'test-open':'schedule'}" ${t?`data-id="${t.id}"`:''}>Сделать следующий шаг ${icon('arrow')}</button></section><button class="focus-collection full" data-action="navigate" data-view="custom" style="text-align:left">${tree()}<div><span class="eyebrow">ВАШ САД</span><h3>${data.trees.find(t=>t.id===state.tree).name} · Уровень ${currentLevel().level}</h3><p>${tenure()} в компании<br>${fmt(state.xp)} XP накоплено</p></div></button>${goalCard()}${activityLink()}`;}
function growthView(){return header('Мой рост',{sub:'HALYK · ДЛЯ СОТРУДНИКОВ'})+`<main class="screen" id="screen">${({A:VariantA,B:VariantB,C:VariantC})[variant]()}</main>`;}
function testRow(t){return `<button class="test-row" data-action="test-open" data-id="${t.id}"><span class="icon-tile ${t.status==='failed'?'coral':''}">${icon(t.status==='passed'?'check':t.status==='failed'?'retry':'book')}</span><div class="grow"><h3>${t.title}</h3><p>${statusName[t.status]}${t.score!==null?' · '+t.score+'%':' · '+t.minutes+' мин'}</p></div>${t.status==='passed'?pill('Готово','check'):xp(t.xp)}${icon('chevron')}</button>`;}
function testsView(){
  const term=state.search.toLowerCase().trim();
  const available=state.tests.filter(t=>state.testTab==='catalog'?!t.required:t.required||state.plan.includes(t.id));
  const filtered=available.filter(t=>(state.filter==='all'||t.status===state.filter)&&(state.category==='Все'||t.category===state.category)&&(!term||(t.title+' '+t.description+' '+t.category).toLowerCase().includes(term)));
  return header('Тесты и навыки')+`<main class="screen" id="screen"><div class="segmented"><button data-action="test-tab" data-tab="required" class="${state.testTab==='required'?'selected':''}">Мой план <small>${state.tests.filter(t=>t.required).length+state.plan.length}</small></button><button data-action="test-tab" data-tab="catalog" class="${state.testTab==='catalog'?'selected':''}">Каталог</button></div><label class="search">${icon('search')}<input id="test-search" aria-label="Найти тест" placeholder="Найти тест или навык" value="${esc(state.search)}"></label>
    ${state.testTab==='required'?`<div class="chips">${[['all','Все'],['new','Не начато'],['passed','Пройдено'],['failed','Повторить']].map(([id,n])=>`<button class="chip ${state.filter===id?'selected':''}" data-action="filter" data-filter="${id}">${n}</button>`).join('')}</div><div class="status-summary">${state.employee.role} · ${filtered.length} тестов</div>`:`<p class="body-copy">Любопытство — тоже навык.<br>Добавьте в план то, что интересно вам.</p><div class="chips">${['Все','IT','Продукт','Лидерство'].map(c=>`<button class="chip ${c===state.category?'selected':''}" data-action="category" data-category="${c}">${c}</button>`).join('')}</div>`}
    ${state.quiz?`<button class="goal-card" style="margin-bottom:13px" data-action="resume-quiz"><span class="icon-tile">${icon('clock')}</span><div class="grow"><div class="goal-title">Продолжить ${test(state.quiz.testId).title}</div><div class="tiny muted">Вопрос ${state.quiz.index+1} · ответы сохранены в этой сессии</div></div>${icon('chevron')}</button>`:''}
    ${filtered.length?state.testTab==='catalog'?filtered.map(t=>`<article class="catalog-card"><div class="row between"><span class="icon-tile">${icon(t.category==='Лидерство'?'people':'spark')}</span>${pill(t.category)}</div><h3>${t.title}</h3><p>${t.description}</p><div class="row bottom between"><div>${xp(t.xp)}<span class="tiny muted" style="margin-left:8px">${t.minutes} мин</span></div><button class="secondary-btn" data-action="${state.plan.includes(t.id)?'test-open':'add-test'}" data-id="${t.id}">${icon(state.plan.includes(t.id)?'check':'plus')}${state.plan.includes(t.id)?'В вашем плане':'В мой план'}</button></div></article>`).join(''):`<section class="test-list">${filtered.map(testRow).join('')}</section>`:`<div class="empty">${icon('search')}<h3>Пока ничего не нашлось</h3><p>Попробуйте другой запрос или фильтр.</p><button class="secondary-btn" data-action="clear-filters">Сбросить фильтры</button></div>`}
  </main>`;
}
function testView(){const t=test(state.selectedTest),q=data.questions[t.questionSet];return header(t.title,{back:'tests'})+`<main class="screen" id="screen"><div class="test-intro-icon">${icon('book')}</div>${pill(t.required?'Для вашей роли':'По вашему выбору')}<h3 class="test-detail-title" style="margin-top:14px">${t.title}</h3><p class="body-copy">${t.description}</p><div class="test-metrics"><div><strong>${q.length}</strong><span>вопросов</span></div><div><strong>${t.passScore}%</strong><span>для прохождения</span></div><div><strong>+${t.xp}</strong><span>XP за результат</span></div></div>
  ${t.status==='failed'?`<div class="card"><div class="row between"><span class="small">Прошлая попытка</span>${pill(`${t.score}% · Повторить`,'retry','coral')}</div><p class="body-copy" style="margin-bottom:0">Ошибки — часть пути. Повторите материал и попробуйте ещё раз.</p></div>`:''}
  ${t.status==='passed'?`<div class="card"><div class="row between"><span class="small">Ваш результат</span>${pill(t.score+'%','check')}</div><p class="body-copy" style="margin-bottom:0">Навык подтверждён. Награда уже учтена в вашем опыте.</p></div><button class="primary-btn full" style="margin-top:22px" data-action="navigate" data-view="tests">К моему плану</button>`:`<ul class="checklist"><li>${icon('check')}Один правильный ответ на вопрос</li><li>${icon('check')}Можно вернуться к предыдущему вопросу</li><li>${icon('check')}Результат и объяснения после завершения</li></ul><button class="primary-btn full" data-action="start-quiz" data-id="${t.id}">${state.quiz?.testId===t.id?'Продолжить тест':'Начать тест'} ${icon('arrow')}</button>`}
  <div class="help-text">${icon('info')}Короткая демо-версия теста. Ответы и результат останутся в этой сессии.</div></main>`;}
function quizView(){const session=state.quiz,t=test(session.testId),questions=data.questions[t.questionSet],q=questions[session.index];return header(t.title,{back:'tests'})+`<main class="screen" id="screen"><div class="quiz-top"><span>Вопрос ${session.index+1} из ${questions.length}</span><span>${pill(t.skill)}</span></div><div class="quiz-progress">${questions.map((_,i)=>`<i class="${i<session.index?'done':i===session.index?'current':''}"></i>`).join('')}</div><div class="eyebrow">ОДИН ПРАВИЛЬНЫЙ ОТВЕТ</div><h3 class="quiz-question">${q.text}</h3><div role="group" aria-label="Варианты ответа">${q.options.map((o,i)=>`<button class="answer ${session.answers[session.index]===i?'selected':''}" data-action="answer" data-answer="${i}" aria-pressed="${session.answers[session.index]===i}"><span class="radio"></span>${o}</button>`).join('')}</div><div class="quiz-actions"><button class="secondary-btn" data-action="question-back" ${session.index===0?'disabled':''} aria-label="Предыдущий вопрос">${icon('back')}</button><button class="primary-btn" data-action="question-next" ${session.answers[session.index]===undefined?'disabled':''}>${session.index===questions.length-1?'Завершить тест':'Дальше'} ${icon('arrow')}</button></div><button class="text-btn" style="margin-top:22px" data-action="navigate" data-view="tests">Сохранить и выйти</button></main>`;}
function resultView(){const r=state.result,t=test(r.testId);return header('Результат теста',{back:'tests'})+`<main class="screen" id="screen"><section class="result-hero ${r.passed?'':'failed'}"><div class="result-medal">${icon(r.passed?'star':'sprout')}</div><h3>${r.passed?'Отличная работа, '+state.employee.firstName+'!':'Каждый шаг — это опыт'}</h3><p>${t.title}</p><div class="result-score">${r.score}%</div><p>${r.correct} из ${r.total} верно · Порог ${t.passScore}%</p><div style="margin-top:14px">${pill(r.passed?'Тест пройден':'Попробуйте ещё раз',r.passed?'check':'retry',r.passed?'':'coral')}</div><div class="reward-card"><div class="row between"><strong>${r.reward?'+'+r.reward+' XP':'Следующий шаг — повторить'}</strong>${r.reward?pill('Уровень '+currentLevel().level):''}</div><p style="margin-top:9px">${r.reward?`${fmt(state.xp)} / ${fmt(nextLevel()?.xp||state.xp)} XP`:'Сначала разберите ответы. XP начисляется за пройденный тест.'}</p>${r.reward?progress(levelProgress()):''}</div></section><div class="section-heading"><h3>Разбор ответов</h3><span class="tiny muted">${r.correct}/${r.total}</span></div>${data.questions[t.questionSet].map((q,i)=>`<div class="feedback-row ${r.answers[i]===q.correct?'':'incorrect'}">${icon(r.answers[i]===q.correct?'check':'info')}<div><strong style="font-weight:500">${q.text}</strong><p class="muted" style="margin-top:5px">${q.explanation}</p></div></div>`).join('')}<button class="primary-btn full" style="margin-top:22px" data-action="${r.passed?'navigate':'start-quiz'}" ${r.passed?'data-view="growth"':`data-id="${t.id}"`}>${r.passed?'Вернуться к дереву':'Попробовать ещё раз'} ${icon('arrow')}</button></main>`;}
function stepRow(step,i){const done=step.done||(step.testId&&test(step.testId).status==='passed');return `<div class="step"><span class="${done?'done':step.testId?'current':''}">${done?icon('check'):i+1}</span><div class="grow"><h3>${step.title}</h3><p>${done?'Навык подтверждён':step.detail}</p>${!done?step.testId?`<button class="text-btn" data-action="test-open" data-id="${step.testId}">К тесту ${icon('arrow')}</button>`:`<button class="text-btn" data-action="${step.activityId?'activity-open':'schedule'}" data-id="${step.activityId||'meeting'}">${step.activityId?'Добавить практику':'Запланировать встречу'} ${icon('arrow')}</button>`:''}</div></div>`;}
function goalsView(){const g=goal(),r=goalReadiness();return header('Моя цель')+`<main class="screen" id="screen"><div class="segmented"><button data-action="goal-picker" data-type="promotion" class="${g.type==='promotion'?'selected':''}">${icon('chart')} Повышение</button><button data-action="goal-picker" data-type="transfer" class="${g.type==='transfer'?'selected':''}">Смена команды</button></div><section class="goal-hero">${pill(g.department,'building')}<h3>${g.title}</h3><p>${g.description}</p><div class="row between"><span class="goal-readiness">${r.percent}%</span><span class="tiny muted">${r.count} из ${g.total} навыков</span></div>${progress(r.percent)}</section><div class="section-heading"><h3>Ваш путь к цели</h3><button class="text-btn" data-action="goal-picker">Изменить</button></div><div class="step-list">${g.steps.map(stepRow).join('')}</div><div class="mentor-card"><div class="eyebrow">С ПОДДЕРЖКОЙ РАСТИ ЛЕГЧЕ</div><h3>${g.type==='promotion'?'Разберите следующий шаг с тимлидом':'Познакомьтесь с новой командой'}</h3><p>${g.type==='promotion'?'Данияр поможет составить план практики и обсудить готовность к новой роли.':'Обсудите ожидания и попробуйте небольшую задачу вместе с будущими коллегами.'}</p><button class="primary-btn" data-action="schedule">${icon('people')}Запланировать 1:1</button></div><div class="help-text">${icon('info')}${g.type==='promotion'?'Повышение обсуждается с руководителем. XP и тесты не заменяют оценку рабочих результатов.':'Переход согласуется с текущим и новым руководителями.'}</div></main>`;}
function profileView(){const e=state.employee;return header('Мой профиль',{action:'demo-profile',actionIcon:'settings'})+`<main class="screen" id="screen"><section class="profile-card"><div class="row"><span class="avatar large">${e.initials}</span><div><h3>${e.name}</h3><div class="role">${e.role}</div>${pill('Сотрудник Halyk','shield')}</div></div><div class="profile-grid"><div><label>КОМАНДА</label><strong>${e.department}</strong></div><div><label>СТАЖ В КОМПАНИИ</label><strong>${tenure()}</strong></div><div><label>РУКОВОДИТЕЛЬ</label><strong>${e.manager}</strong></div><div><label>ГОРОД</label><strong>${e.city}</strong></div></div><div class="profile-stats"><div><strong>${currentLevel().level}</strong><span>уровень</span></div><div><strong>${fmt(state.xp)}</strong><span>опыта XP</span></div><div><strong>${state.tests.filter(t=>t.status==='passed').length}</strong><span>тестов пройдено</span></div></div></section><div class="section-heading"><h3>Всё о вашем развитии</h3></div><section class="menu-list">${[
    ['award','Навыки и сертификаты','Навыков: '+e.skills.length+' · сертификатов: '+e.certificates.length,'profile-detail','skills'],
    ['book','Тесты и история попыток','Все результаты в одном месте','profile-detail','attempts'],
    ['target','Цель и план развития',goal().title,'navigate','goals'],
    ['spark','Вклад и достижения',state.contributions.filter(c=>c.status==='confirmed').length+' подтверждения','navigate','activities'],
    ['people','Встречи и обратная связь',state.meetings.length?'Запланировано встреч: '+state.meetings.length:'Ваши разговоры о росте','profile-detail','meetings'],
    ['person','Данные сотрудника',e.employeeId,'profile-detail','employee']
  ].map(([i,t,d,a,id])=>`<button class="menu-row" data-action="${a}" data-id="${id}" data-view="${id}">${icon(i)}<div><h3>${t}</h3><p>${d}</p></div>${icon('chevron')}</button>`).join('')}</section><div class="section-heading"><h3>Подключения</h3></div><section class="menu-list"><button class="menu-row" data-action="jira-settings">${icon('jira')}<div><h3>Jira</h3><p>${state.jiraConnected?'Подключено · Digital Banking':'Не подключено'}</p></div>${pill('Демо')}${icon('chevron')}</button><button class="menu-row" data-action="profile-detail" data-id="privacy">${icon('shield')}<div><h3>Данные и доступ</h3><p>Что хранит система и кто это видит</p></div>${icon('chevron')}</button></section></main>`;}
function customView(){const d=state.draft;return header('Моё дерево',{back:'growth'})+`<main class="screen" id="screen"><section class="custom-hero ${d.theme}">${pill('Уровень '+currentLevel().level,'star')}${tree({species:d.tree,theme:d.theme})}<div class="tree-caption">${tenure()} в Halyk · размер зависит от стажа</div></section><div class="tenure-scale">${[6,12,24].map(m=>`<div class="${m===state.employee.tenureMonths?'selected':''}">${tree({species:d.tree,theme:d.theme,months:m,miniature:true})}${tenure(m)}${m===state.employee.tenureMonths?' · Вы':''}</div>`).join('')}</div><div class="section-heading"><h3>Характер вашего дерева</h3></div><div class="tree-choices">${data.trees.map(t=>`<button class="tree-choice ${d.tree===t.id?'selected':''}" data-action="tree-choice" data-id="${t.id}" aria-label="Выбрать ${t.name}" aria-pressed="${d.tree===t.id}">${d.tree===t.id?`<span class="choice-check">${icon('check')}</span>`:state.xp<t.xp?`<span class="choice-check">${icon('lock')}</span>`:''}${tree({species:t.id,theme:d.theme,miniature:true})}${t.name}</button>`).join('')}</div><div class="section-heading"><h3>Маленький мир вокруг</h3>${xp(state.xp).replace('+','')}</div><div class="theme-choices">${data.themes.map(t=>`<button class="theme-choice ${d.theme===t.id?'selected':''}" data-action="theme-choice" data-id="${t.id}" aria-label="Тема ${t.name}" aria-pressed="${d.theme===t.id}"><span class="theme-swatch ${t.id}">${icon(state.xp<t.xp?'lock':t.id==='night'?'moon':t.id==='autumn'?'leaf':'sun')}</span>${t.name}<small>${state.xp<t.xp?t.xp+' XP':'Доступно'}</small></button>`).join('')}</div><div class="help-text">${icon('spark')}${state.xp<1600?`Ещё ${fmt(1600-state.xp)} XP до Ночного сада.`:'Ночной сад открыт. Вы заслужили свою магию.'} Опыт не тратится при выборе темы.</div><div class="custom-save"><button class="primary-btn full" data-action="save-custom">Сохранить оформление ${icon('check')}</button></div></main>`;}
function historyItem(c){return `<article class="history-item"><div class="row"><span class="icon-tile ${c.type==='jira'?'jira-icon':''}">${icon(data.activities.find(a=>a.id===c.type)?.icon||'book')}</span><div class="grow"><h3>${esc(c.title)}</h3><p>${esc(c.detail)}</p></div></div><div class="row between">${pill(c.status==='confirmed'?'Подтверждено':c.status==='scheduled'?'Запланировано':'Ждёт подтверждения',c.status==='confirmed'?'check':'clock',c.status==='confirmed'?'':'gold')}${xp(c.xp)}</div>${c.status!=='confirmed'?`<button class="text-btn" data-action="confirm-preview" data-id="${c.id}">Подтвердить результат · демо ${icon('arrow')}</button>`:''}</article>`;}
function activitiesView(){return header('Опыт и вклад',{back:'growth'})+`<main class="screen" id="screen"><section class="activities-xp">${tree()}<div class="grow"><span class="tiny muted">ВАШ ОПЫТ РАСТЁТ</span><h3>${fmt(state.xp)} <span class="small">XP</span></h3><div class="tiny muted">Уровень ${currentLevel().level} · ${nextLevel()?fmt(nextLevel().xp-state.xp)+' XP до следующего':'Все уровни открыты'}</div>${progress(levelProgress())}</div></section><div class="section-heading"><h3>Расти можно по-разному</h3></div><div class="activity-grid">${data.activities.map(a=>`<button class="activity-card" data-action="activity-open" data-id="${a.id}">${icon(a.icon)}<h3>${a.title}</h3><p>+${a.xp} XP</p></button>`).join('')}</div><div class="help-text">${icon('info')}Опыт начисляется за прохождение или подтверждённый вклад. Один результат — одна награда.</div><div class="card jira-card"><div class="row"><span class="icon-tile jira-icon">${icon('jira')}</span><div class="grow"><strong class="small">Jira · ${data.jira.workspace}</strong><p class="tiny muted" style="margin-top:5px">${state.jiraConnected?'Синхронизация '+state.lastSync:'Подключение отключено'} · демо</p></div><button class="icon-btn" data-action="jira-sync" aria-label="Синхронизировать Jira">${icon('retry')}</button></div></div><div class="section-heading"><h3>История вклада</h3><span class="tiny muted">${state.contributions.length} записей</span></div>${state.contributions.map(historyItem).join('')}</main>`;}

const views={bank:bankView,growth:growthView,tests:testsView,test:testView,quiz:quizView,result:resultView,goals:goalsView,profile:profileView,custom:customView,activities:activitiesView};
function render(preserve=false){
  if(!state.isEmployee&&state.view!=='bank')state.view='bank';
  if(state.view==='custom'&&!state.draft)state.draft={tree:state.tree,theme:state.theme};
  const top=document.querySelector('#screen')?.scrollTop||0;
  app.innerHTML=views[state.view]()+bottomNav();
  if(preserve)document.querySelector('#screen').scrollTop=top;
  document.title=`Halyk · ${state.view==='bank'?'Суперапп':'Мой рост'}`;
  renderStudio();
}
function renderStudio(){
  document.querySelector('#demo-controls').innerHTML=`<label for="employee-select">ДЕМО-ПРОФИЛЬ</label><select id="employee-select">${data.employees.map(e=>`<option value="${e.id}" ${state.isEmployee&&state.employee.id===e.id?'selected':''}>${e.firstName} · ${tenure(e.tenureMonths)} в компании</option>`).join('')}<option value="guest" ${!state.isEmployee?'selected':''}>Клиент · не сотрудник</option></select><button class="text-btn" data-action="reset">${icon('retry')}Начать демо заново</button>`;
  const info={bank:['01','Всё начинается здесь','«Мой рост» живёт среди сервисов Halyk и появляется только у сотрудника после авторизации.'],growth:['02','Ваше место роста',data.variants.find(v=>v.id===variant).description],tests:['03','Интерес ведёт вперёд','Обязательная база для вашей роли и свободный выбор навыков для следующего шага.'],test:['03','Знать, куда расти','Короткие вопросы, прозрачный порог прохождения и полезный разбор результата.'],quiz:['03','В своём темпе','Ответы можно менять. Прервитесь и вернитесь — прогресс сохранён в этой сессии.'],result:['03','Каждый шаг заметен','Пройденный тест добавляет XP один раз. Ошибки помогают выбрать, что повторить.'],goals:['04','Будущее с маршрутом','Повышение или новая команда: понятные навыки, практика и разговор с руководителем.'],profile:['05','Ваша история целиком','Роль, команда, стаж, навыки, результаты и все данные о развитии в одном месте.'],custom:['06','Дерево с характером','Стаж меняет размер. Опыт открывает виды и темы. Вы выбираете своё настроение.'],activities:['07','Вклад имеет значение','Тесты, review, наставничество и встречи — разные способы развиваться.']};
  const [num,title,desc]=info[state.view];
  const snapshot={view:state.view,variant,employee:state.isEmployee?state.employee.id:'guest',tenureMonths:state.employee.tenureMonths,xp:state.xp,level:currentLevel().level,goalId:state.goalId,tree:state.tree,theme:state.theme,plan:state.plan,tests:{passed:countStatus('passed'),new:countStatus('new'),failed:countStatus('failed')},quiz:state.quiz,attempts:state.attempts,meetings:state.meetings,contributions:state.contributions.map(c=>({id:c.id,status:c.status})),jiraConnected:state.jiraConnected};
  document.querySelector('#context-panel').innerHTML=`<div class="context-kicker">${num} — СЦЕНАРИЙ</div><h2>${title}</h2><p>${desc}</p><div class="context-line"></div><div class="context-point">${icon('shield')}Только демонстрационные данные</div><div class="context-point">${icon('sprout')}Опыт ≠ карьерный грейд</div><div class="context-point">${halykIcon}<span>Halyk всегда под рукой</span></div><details class="state-detail"><summary>Состояние прототипа</summary><pre>${esc(JSON.stringify(snapshot,null,2))}</pre></details>`;
  document.querySelector('#prototype-switcher').innerHTML=`<button data-action="variant" data-direction="-1" aria-label="Предыдущий вариант">${icon('back')}</button><span><small>ПРОТОТИП</small>${variant} · ${data.variants.find(v=>v.id===variant).name}</span><button data-action="variant" data-direction="1" aria-label="Следующий вариант">${icon('chevron')}</button>`;
  console.debug('[Halyk prototype state]',snapshot);
}
function navigate(view){if(!views[view]||(!state.isEmployee&&view!=='bank'))return;if(view==='custom'&&state.view!=='custom')state.draft={tree:state.tree,theme:state.theme};state.view=view;closeModal(false);render();}
function toast(message){const el=document.querySelector('#toast');clearTimeout(toastTimer);el.textContent=message;el.classList.add('visible');toastTimer=setTimeout(()=>el.classList.remove('visible'),3500);}
function setVariant(direction){const index=data.variants.findIndex(v=>v.id===variant);variant=data.variants[(index+direction+data.variants.length)%data.variants.length].id;const url=new URL(location.href);url.searchParams.set('variant',variant);url.searchParams.set('view','growth');history.replaceState({},'',url);if(state.isEmployee)state.view='growth';render();}
function openModal(title,body,type='info'){
  modalReturnFocus=document.activeElement;modalType=type;
  modalRoot.innerHTML=`<div class="modal-backdrop" data-action="modal-backdrop"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title" tabindex="-1"><div class="modal-handle"></div><div class="modal-header"><h3 id="modal-title">${title}</h3><button class="icon-btn" data-action="close-modal" aria-label="Закрыть">${icon('close')}</button></div>${body}</section></div>`;
  app.inert=true;
  modalRoot.querySelector('.modal').focus();
}
function closeModal(restore=true){modalRoot.innerHTML='';modalType=null;app.inert=false;if(restore&&modalReturnFocus?.isConnected)modalReturnFocus.focus();}
function award(id,amount){if(state.earned.includes(id))return 0;state.earned.push(id);state.xp+=amount;return amount;}
function openTest(id){state.selectedTest=id;navigate('test');}
function startQuiz(id){
  if(state.quiz&&state.quiz.testId!==id){openModal('Продолжить или начать новый?',`<p class="body-copy">У вас есть незавершённый тест «${test(state.quiz.testId).title}». Начало нового теста заменит текущую попытку.</p><div class="modal-actions"><button class="secondary-btn" data-action="resume-quiz">Продолжить</button><button class="primary-btn" data-action="replace-quiz" data-id="${id}">Начать новый</button></div>`);return;}
  if(!state.quiz)state.quiz={testId:id,index:0,answers:[]};
  if(!test(id).required&&!state.plan.includes(id))state.plan.push(id);
  navigate('quiz');
}
function finishQuiz(){const q=state.quiz,t=test(q.testId),questions=data.questions[t.questionSet],correct=questions.filter((question,i)=>question.correct===q.answers[i]).length,score=Math.round(correct/questions.length*100),passed=score>=t.passScore;
  t.score=score;t.status=passed?'passed':'failed';
  if(passed){const skill=state.employee.skills.find(s=>s.name===t.skill);if(skill)skill.score=Math.max(skill.score,score);else state.employee.skills.push({name:t.skill,score});}
  const reward=passed?award('test-'+t.id,t.xp):0;
  state.result={testId:t.id,score,correct,total:questions.length,passed,reward,answers:[...q.answers]};
  state.attempts.unshift({testId:t.id,score,passed});
  if(passed&&reward)state.contributions.unshift({id:'test-'+t.id,title:t.title,detail:'Тест навыка · '+score+'%',type:'test',status:'confirmed',xp:reward,date:'Сегодня'});
  state.quiz=null;navigate('result');
}
function goalPicker(type){const filtered=type?data.goals.filter(g=>g.type===type):data.goals;openModal('Куда хотите расти?',`<p class="body-copy">Выберите направление. План подстроится под требования новой роли.</p>${filtered.map(g=>`<button class="goal-choice ${state.goalId===g.id?'selected':''}" data-action="set-goal" data-id="${g.id}"><h3>${g.title}</h3><p>${g.description}</p>${pill(g.department)}${state.goalId===g.id?pill('Ваша цель','check'):''}</button>`).join('')}<div class="help-text">${icon('info')}Сохранение цели не запускает перевод или повышение.</div>`,'goal');}
function schedule(){openModal('Встреча о вашем росте',`<div class="row"><span class="avatar">ДА</span><div><strong class="small">${state.employee.manager}</strong><p class="tiny muted" style="margin-top:5px">Тимлид · 30 минут</p></div></div><form id="meeting-form"><label class="field">Тема встречи<input name="topic" value="${goal().type==='promotion'?'Мой следующий шаг к Senior':'Карьерный переход: '+esc(goal().department)}" required maxlength="120"></label><div class="small muted" style="margin:17px 0 10px">Удобное время</div>${data.meetingSlots.map((slot,i)=>`<label class="slot"><input type="radio" name="slot" value="${slot}" ${i===0?'checked':''}>${slot}</label>`).join('')}<div class="help-text">${icon('info')}+100 XP после встречи и подтверждения тимлидом.</div><button class="primary-btn full" style="margin-top:20px" type="submit">Запланировать встречу ${icon('calendar')}</button></form>`,'meeting');}
function activityOpen(id){const a=data.activities.find(a=>a.id===id);if(id==='test'){state.testTab='required';navigate('tests');return;}if(id==='meeting'){schedule();return;}if(id==='jira'){navigate('activities');jiraSettings();return;}openModal(a.title,`<div class="row between"><span class="icon-tile">${icon(a.icon)}</span>${xp(a.xp)}</div><p class="body-copy">${a.detail}. После подтверждения руководителем вклад появится в истории.</p><form id="contribution-form" data-kind="${id}"><label class="field">Что вы сделали?<input name="title" required maxlength="120" placeholder="${id==='review'?'Например, review PR #152':id==='mentoring'?'Например, разбор задачи с коллегой':'Например, доклад о React patterns'}"></label><label class="field">Результат или ссылка<textarea name="detail" required maxlength="400" placeholder="Расскажите, чем ваш вклад помог команде"></textarea></label><button type="submit" class="primary-btn full">Отправить на подтверждение ${icon('arrow')}</button></form>`,'contribution');}
function jiraSettings(){openModal('Подключение Jira',`<div class="row"><span class="icon-tile jira-icon">${icon('jira')}</span><div><strong class="small">${data.jira.workspace}</strong><p class="tiny muted" style="margin-top:5px">Проект ${data.jira.project} · ${state.jiraConnected?'подключено':'не подключено'}</p></div></div><p class="body-copy">Завершённые задачи появляются в истории вклада. Тимлид подтверждает результат перед начислением опыта.</p><div class="demo-warning">Демонстрация интеграции: синхронизация добавляет одну заранее подготовленную задачу из mock-data.json. Доступ к реальной Jira не используется.</div><div class="modal-actions"><button class="secondary-btn" data-action="jira-toggle">${state.jiraConnected?'Отключить':'Подключить'}</button><button class="primary-btn" data-action="jira-sync" ${state.jiraConnected?'':'disabled'}>Синхронизировать</button></div>`,'jira');}
function profileDetail(id){const e=state.employee;
  if(id==='skills')openModal('Навыки и сертификаты',`${e.skills.map(s=>`<div class="skill-row"><div class="row between"><strong>${s.name}</strong><span class="muted">${s.score}%</span></div>${progress(s.score)}</div>`).join('')}<div class="section-heading"><h3>Сертификаты</h3></div>${e.certificates.map(c=>`<div class="certificate">${icon('award')}${c}</div>`).join('')}`);
  if(id==='attempts')openModal('История тестов',`${state.attempts.map(a=>`<div class="attempt-row"><div>${test(a.testId).title}<p>Сегодня · новая попытка</p></div>${pill(a.score+'%',a.passed?'check':'retry',a.passed?'':'coral')}</div>`).join('')}${data.tests.filter(t=>t.score!==null).map(t=>`<div class="attempt-row"><div>${t.title}<p>Предыдущий результат</p></div>${pill(t.score+'%',t.status==='passed'?'check':'retry',t.status==='passed'?'':'coral')}</div>`).join('')}`);
  if(id==='employee')openModal('Данные сотрудника',`<div class="demo-warning">Вымышленный профиль для демонстрации.</div>${[['Полное имя',e.name],['Идентификатор',e.employeeId],['Должность',e.role],['Подразделение',e.department],['Команда',e.team],['Руководитель',e.manager],['Начало работы',e.startDate],['Стаж',tenure()],['Город',e.city],['Рабочая почта',e.email]].map(([label,value])=>`<div class="attempt-row"><span class="muted">${label}</span><strong style="font-size:10px;font-weight:500;text-align:right">${value}</strong></div>`).join('')}`);
  if(id==='meetings')openModal('Встречи и обратная связь',`${state.meetings.length?state.meetings.map(m=>`<div class="card"><h3 class="small">${esc(m.topic)}</h3><p class="body-copy">${m.slot}<br>${e.manager}</p>${pill('Запланировано','calendar')}</div>`).join(''):`<div class="empty">${icon('people')}<h3>Начните с разговора</h3><p>На встрече можно обсудить цель,<br>сложную задачу или обратную связь.</p></div>`}<button class="primary-btn full" data-action="schedule" style="margin-top:15px">Запланировать 1:1</button>`);
  if(id==='privacy')openModal('Данные и доступ',`<p class="body-copy">Ваш профиль объединяет данные, которые помогают планировать развитие.</p><ul class="modal-list"><li>HR-профиль: роль, подразделение, руководитель и стаж.</li><li>Развитие: тесты, попытки, навыки, сертификаты и цели.</li><li>Вклад: встречи, code review, наставничество и задачи Jira.</li><li>Игровой прогресс: XP, уровень и оформление дерева.</li></ul><div class="card"><h3 class="small">Кто видит данные</h3><p class="body-copy">Вы — весь свой профиль. Руководитель — план развития и подтверждаемый вклад. HR — карьерные цели и навыки.</p></div><div class="help-text">${icon('info')}В прототипе данные не сохраняются и никуда не отправляются. Перезагрузка сбрасывает изменения.</div>`);
}
function demoProfile(){openModal('Демо-профиль',`<div class="demo-warning">Смена профиля перезапускает демо. Так можно сравнить размер дерева по стажу и проверить вход сотрудника.</div>${data.employees.map(e=>`<button class="goal-choice" data-action="employee" data-id="${e.id}"><h3>${e.name}</h3><p>${e.role}</p>${pill(tenure(e.tenureMonths)+' в компании')}${pill(fmt(e.xp)+' XP')}</button>`).join('')}<button class="goal-choice" data-action="employee" data-id="guest"><h3>Клиент Halyk</h3><p>Не сотрудник · сервис «Мой рост» скрыт</p></button>`);}

document.addEventListener('click',event=>{
  const el=event.target.closest('[data-action]');if(!el||el.disabled)return;
  const {action,id,view}=el.dataset;
  if(action==='navigate'){navigate(view);return;}
  if(action==='close-modal'){closeModal();return;}
  if(action==='modal-backdrop'){if(event.target===el)closeModal();return;}
  if(action==='variant'){setVariant(Number(el.dataset.direction));return;}
  if(action==='reset'){reset(state.isEmployee?state.employee.id:'guest');toast('Демо началось заново');return;}
  if(action==='employee'){reset(id);return;}
  if(action==='demo-profile'){demoProfile();return;}
  if(action==='test-open'){openTest(id);return;}
  if(action==='status-filter'){state.filter=el.dataset.filter;state.testTab='required';state.category='Все';state.search='';navigate('tests');return;}
  if(action==='test-tab'){state.testTab=el.dataset.tab;state.filter='all';state.category='Все';state.search='';render();return;}
  if(action==='filter'){state.filter=el.dataset.filter;render(true);return;}
  if(action==='category'){state.category=el.dataset.category;render(true);return;}
  if(action==='clear-filters'){state.filter='all';state.search='';state.category='Все';render();return;}
  if(action==='add-test'){if(!state.plan.includes(id))state.plan.push(id);render(true);toast('«'+test(id).title+'» добавлен в ваш план');return;}
  if(action==='start-quiz'){startQuiz(id);return;}
  if(action==='replace-quiz'){state.quiz=null;startQuiz(id);return;}
  if(action==='resume-quiz'){navigate('quiz');return;}
  if(action==='answer'){state.quiz.answers[state.quiz.index]=Number(el.dataset.answer);render(true);document.querySelector(`[data-action="answer"][data-answer="${el.dataset.answer}"]`).focus({preventScroll:true});return;}
  if(action==='question-back'){state.quiz.index--;render();return;}
  if(action==='question-next'){if(state.quiz.answers[state.quiz.index]===undefined)return;const t=test(state.quiz.testId);if(state.quiz.index===data.questions[t.questionSet].length-1)finishQuiz();else{state.quiz.index++;render();}return;}
  if(action==='goal-picker'){goalPicker(el.dataset.type);return;}
  if(action==='set-goal'){state.goalId=id;closeModal(false);navigate('goals');toast('Новая цель сохранена. Ваш план обновлён.');return;}
  if(action==='tree-choice'||action==='theme-choice'){const option=(action==='tree-choice'?data.trees:data.themes).find(x=>x.id===id);if(state.xp<option.xp){toast(`Ещё ${fmt(option.xp-state.xp)} XP, чтобы открыть «${option.name}»`);return;}state.draft[action==='tree-choice'?'tree':'theme']=id;render(true);return;}
  if(action==='save-custom'){state.tree=state.draft.tree;state.theme=state.draft.theme;navigate('growth');toast('Ваше дерево обрело новый характер');return;}
  if(action==='schedule'){schedule();return;}
  if(action==='activity-open'){activityOpen(id);return;}
  if(action==='confirm-preview'){const c=state.contributions.find(c=>c.id===id);openModal('Подтвердить результат',`<div class="demo-warning">Действие руководителя в демо. В реальном приложении сотрудник не подтверждает собственный вклад.</div><h3 class="small">${esc(c.title)}</h3><p class="body-copy">${esc(c.detail)}</p><div class="row between"><span class="small muted">После подтверждения</span>${xp(c.xp)}</div><button class="primary-btn full" style="margin-top:20px" data-action="confirm-contribution" data-id="${id}">Подтвердить · демо</button>`);return;}
  if(action==='confirm-contribution'){const c=state.contributions.find(c=>c.id===id);const earned=award(c.id,c.xp);c.status='confirmed';c.detail='Подтвердил: '+state.employee.manager;closeModal(false);render(true);toast(earned?`Вклад подтверждён. +${earned} XP в вашу копилку`:'Этот вклад уже учтён');return;}
  if(action==='jira-settings'){jiraSettings();return;}
  if(action==='jira-toggle'){state.jiraConnected=!state.jiraConnected;closeModal(false);render(true);toast(state.jiraConnected?'Демо-подключение Jira активно':'Демо-подключение Jira отключено');return;}
  if(action==='jira-sync'){if(!state.jiraConnected){jiraSettings();return;}const added=!state.jiraSynced;if(added){state.contributions.unshift(clone(data.jira.newTask));state.jiraSynced=true;}state.lastSync='11:24';closeModal(false);render(true);toast(added?'Jira синхронизирована: 1 новый результат ждёт подтверждения':'Всё актуально. Новых результатов нет.');return;}
  if(action==='profile-detail'){profileDetail(id);return;}
  if(action==='notifications'){openModal('Хорошие новости',`<div class="card"><div class="row">${icon('sprout')}<h3 class="small">У вас есть следующий шаг</h3></div><p class="body-copy">${nextTest()?.title||'Все тесты завершены'} — небольшая инвестиция в ваше развитие.</p><button class="text-btn" data-action="navigate" data-view="tests">Открыть мой план ${icon('arrow')}</button></div><div class="card"><h3 class="small">Ваш вклад ждёт подтверждения</h3><p class="body-copy">${state.contributions.filter(c=>c.status!=='confirmed').length} записей в истории вклада.</p><button class="text-btn" data-action="navigate" data-view="activities">Посмотреть ${icon('arrow')}</button></div>`);return;}
  if(action==='all-services'){openModal('Сервисы Halyk',`<div class="bank-services" style="margin-top:0">${data.bank.services.map(s=>`<button class="bank-service" data-action="bank-service" data-name="${s.name}">${icon(s.icon)}${s.name}</button>`).join('')}</div>${state.isEmployee?`<button class="goal-card" style="margin-top:16px" data-action="navigate" data-view="growth"><span class="icon-tile">${icon('sprout')}</span><div class="grow"><strong class="small">Мой рост</strong><p class="tiny muted" style="margin-top:5px">Для сотрудников Halyk</p></div>${icon('chevron')}</button>`:''}`);return;}
  if(action==='bank-service'){const name=el.dataset.name;if(name==='Главная')return;if(name==='Карты'||name==='Мой банк'){openModal('Мой банк',`<div class="bank-product"><span class="pill">${data.bank.card}</span><h3>•••• ${data.bank.lastDigits}</h3><strong>${fmt(data.bank.balance)} ₸</strong><p class="small muted">Демонстрационный баланс</p></div><button class="secondary-btn full" style="margin-top:17px" data-action="close-modal">Вернуться на главную</button>`);}else{openModal(name,`<div class="empty">${icon(data.bank.services.find(s=>s.name===name)?.icon||'qr')}<h3>${name} в Halyk</h3><p>Это контекст банковского супераппа.<br>Интерактивный сценарий развития доступен в «Мой рост».</p></div>${state.isEmployee?`<button class="primary-btn full" data-action="navigate" data-view="growth">Открыть Мой рост ${icon('arrow')}</button>`:''}`);}return;}
});
document.addEventListener('input',event=>{
  if(event.target.id==='test-search'){const position=event.target.selectionStart;state.search=event.target.value;render(true);const input=document.querySelector('#test-search');input.focus({preventScroll:true});input.setSelectionRange(position,position);}
  if(event.target.id==='bank-search'){const term=event.target.value.toLowerCase();document.querySelectorAll('.bank-service,.service-small').forEach(el=>el.hidden=!el.textContent.toLowerCase().includes(term));const entry=document.querySelector('.growth-entry');if(entry)entry.hidden=!!term&&!('рост развитие сотрудники навыки'.includes(term));}
});
document.addEventListener('change',event=>{if(event.target.id==='employee-select')reset(event.target.value);});
document.addEventListener('submit',event=>{
  event.preventDefault();const form=event.target,values=new FormData(form);
  if(form.id==='meeting-form'){const topic=String(values.get('topic')).trim(),slot=String(values.get('slot'));if(!topic)return;const id='meeting-'+slot;if(state.contributions.some(c=>c.id===id)){toast('Встреча на это время уже запланирована');return;}state.meetings.push({id,topic,slot});state.contributions.unshift({id,title:'1:1 · '+topic,detail:slot+' · '+state.employee.manager,type:'meeting',status:'scheduled',xp:100,date:slot});closeModal(false);render(true);toast('Встреча запланирована на '+slot);}
  if(form.id==='contribution-form'){const title=String(values.get('title')).trim(),detail=String(values.get('detail')).trim();if(!title||!detail)return;const kind=form.dataset.kind;state.contributions.unshift({id:'contribution-'+crypto.randomUUID(),title,detail,type:kind,status:'pending',xp:data.activities.find(a=>a.id===kind).xp,date:'Сегодня'});closeModal(false);navigate('activities');toast('Ваш вклад отправлен на подтверждение');}
});
document.addEventListener('keydown',event=>{
  if(modalType){if(event.key==='Escape'){closeModal();return;}if(event.key==='Tab'){const targets=[...modalRoot.querySelectorAll('button:not([disabled]), input, select, textarea, [tabindex="0"]')];const first=targets[0],last=targets.at(-1);if(event.shiftKey&&(document.activeElement===first||document.activeElement===modalRoot.querySelector('.modal'))){event.preventDefault();last?.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}}return;}
  if(['INPUT','TEXTAREA','SELECT','BUTTON'].includes(document.activeElement?.tagName)||document.activeElement?.isContentEditable)return;
  if(document.documentElement.dataset.prototype==='true'&&['ArrowLeft','ArrowRight'].includes(event.key)){event.preventDefault();setVariant(event.key==='ArrowLeft'?-1:1);}
  if((event.key==='Enter'||event.key===' ')&&event.target.matches('[role="button"][data-action]')){event.preventDefault();event.target.click();}
});
reset(data.employees.some(e=>e.id===qs.get('employee'))?qs.get('employee'):'aizhan',qs.get('view')==='growth'||qs.has('variant')?'growth':'bank');
