import { useEffect, useRef, useState } from 'react';
import { Icon } from './Icon';
import { SkillTree, levelName } from './SkillTree';
import { PeopleView } from './PeopleView';
import Assessment from './Assessment';
import { CATEGORIES, TESTS, PASS_SCORE, initialState, restoreState, getEmployee, getMonthlyAttempt, getMustHaveTests, submitTest, nextMonth } from './domain';

const STORAGE='career-quest-tree-v1';
const categoryIcon={backend:'code-xml',data:'database',product:'lightbulb',communication:'messages-square',leadership:'users'};
const categoryLabel=id=>CATEGORIES.find(c=>c.id===id)?.label||id;
const monthName=month=>new Date(`${month}-01T12:00:00`).toLocaleDateString('ru-RU',{month:'long',year:'numeric'}).replace(' г.','');
const dateLabel=date=>new Date(date).toLocaleDateString('ru-RU',{day:'numeric',month:'long',year:'numeric'});
const navItems=[['tree','sprout','Моё дерево'],['catalog','book-open','Каталог тестов'],['results','chart-no-axes-combined','Мои результаты'],['meetings','users','Встречи и ревью'],['points','star','Мои баллы']];
function load(){try{return restoreState(localStorage.getItem(STORAGE));}catch{return initialState();}}

export function App(){
 const [state,setState]=useState(load),[page,setPage]=useState('tree'),[role,setRole]=useState('employee');
 const [modal,setModal]=useState(null),[assessment,setAssessment]=useState(null),[freshSkill,setFreshSkill]=useState(null),[treeRevision,setTreeRevision]=useState(0);
 const [viewEmployee,setViewEmployee]=useState(null),[toast,setToast]=useState(''),[storageError,setStorageError]=useState(false);
 const employee=getEmployee(state,state.currentEmployeeId),viewed=getEmployee(state,viewEmployee)||employee;
 const attempt=getMonthlyAttempt(state,employee.id);
 useEffect(()=>{try{localStorage.setItem(STORAGE,JSON.stringify(state));setStorageError(false);}catch{setStorageError(true);}},[state]);
 useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(timer);},[toast]);
 const navigate=p=>{setPage(p);setViewEmployee(null);setModal(null);window.scrollTo({top:0,behavior:'instant'});};
 const changeRole=r=>{setRole(r);setViewEmployee(null);setPage('tree');setModal(null);};
 const openTest=test=>{if(role!=='employee')return;if(attempt){setModal({kind:'quota'});return;}setAssessment(test);};
 const submit=answers=>{const {state:updated,result}=submitTest(state,{employeeId:employee.id,testId:assessment.id,answers,attemptId:crypto.randomUUID(),submittedAt:`${state.month}-01T10:00:00.000Z`});setState(updated);setAssessment(null);setFreshSkill(result.passed?result.skillId:null);setModal({kind:'result',result,newResult:true});};
 const exportPeople=people=>{const rows=[['Сотрудник','Отдел','Роль','Навыки','Средний результат'],...people.map(e=>[e.name,e.department,e.role,e.skills.length,e.history.length?Math.round(e.history.reduce((s,h)=>s+h.score,0)/e.history.length):''])];const content='\uFEFF'+rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(';')).join('\r\n');setModal({kind:'export',content,count:people.length});};
 const scopeTitle=role==='hr'?'HR · Вся компания':'Руководитель · Моя команда';
 const treeFor=e=><SkillTree key={`${e.id}-${treeRevision}`} employee={e} freshSkill={freshSkill} onSkill={skill=>setModal({kind:'skill',skill,employee:e})} onList={()=>setModal({kind:'skills',employee:e})}/>;
 return <div className="app-shell">
  <aside className="sidebar"><button className="brand" onClick={()=>navigate('tree')} aria-label="Career Quest — главная"><span className="brand-mark">H</span><span><b>Career Quest</b><small>Развиваем людей<br/>сегодня для сильного завтра</small></span></button><nav className="side-nav" aria-label="Основная навигация">{role==='employee'?navItems.map(([id,icon,label])=><button key={id} className={page===id?'active':''} onClick={()=>navigate(id)}><Icon name={icon}/>{label}</button>):<><button className="active" onClick={()=>{setViewEmployee(null);setPage('tree');}}><Icon name="users"/>{role==='hr'?'Все сотрудники':'Моя команда'}</button><button onClick={()=>setModal({kind:'methodology'})}><Icon name="shield-check"/>Как считаются навыки</button></>}</nav><div className="sidebar-bottom"><button className="side-person" onClick={()=>role==='employee'?navigate('profile'):setModal({kind:'settings'})}><span className="avatar">{role==='employee'?employee.initials:role==='hr'?'HR':'АС'}</span><span><b>{role==='employee'?employee.name.split(' ')[0]:role==='hr'?'HR-партнёр':'Айгерим'}</b><small>{role==='employee'?`${employee.role} · ${employee.grade}`:scopeTitle}</small><small>{role==='employee'?`${employee.tenure} в банке`:'Демонстрационный кабинет'}</small></span></button><button className="halyk-return" onClick={()=>setModal({kind:'halyk'})}><span className="halyk-symbol">H</span><span><b>Halyk</b><small>Вернуться в суперапп</small></span><Icon name="arrow-right" size={17}/></button></div></aside>
  <main className="main-content"><header className="topbar"><div className="breadcrumb"><span>Моя карьера</span><span>/</span><b>{role!=='employee'?scopeTitle:page==='tree'?'Дерево возможностей':({catalog:'Каталог тестов',results:'Мои результаты',meetings:'Встречи и ревью',points:'Мои баллы',advisor:'Советник',profile:'Профиль'})[page]}</b></div><button className="mobile-brand" onClick={()=>navigate('tree')}><span className="brand-mark">H</span><b>Career Quest</b></button><div className="top-actions"><button className="demo-pill" onClick={()=>setModal({kind:'settings'})}>Демо · {`01.${state.month.slice(5)}.${state.month.slice(0,4)}`}<Icon name="settings-2" size={14}/></button><label className="role-select"><span className="sr-only">Режим просмотра</span><select aria-label="Режим просмотра" value={role} onChange={e=>changeRole(e.target.value)}><option value="employee">Сотрудник</option><option value="manager">Руководитель</option><option value="hr">HR · Полный доступ</option></select></label><button className="avatar top-avatar" aria-label="Открыть профиль" onClick={()=>role==='employee'?navigate('profile'):setModal({kind:'settings'})}>{role==='employee'?employee.initials:role==='hr'?'HR':'АС'}</button></div></header>
  {storageError&&<p role="alert" className="storage-warning">Браузер запретил сохранение. Прогресс доступен до закрытия страницы.</p>}
  {role!=='employee'?(viewEmployee?<><button className="text-button back-link" onClick={()=>setViewEmployee(null)}><Icon name="arrow-left" size={18}/>Назад к сотрудникам</button><PageHeading title={`Дерево: ${viewed.name}`} subtitle={`${viewed.role} · ${viewed.grade} · ${viewed.department}`}/><div className="person-drilldown">{treeFor(viewed)}<section className="panel"><h2>Подтверждения навыков</h2><History employee={viewed} onOpen={result=>setModal({kind:'result',result})}/><div className="info-note"><Icon name="target"/><div><b>Карьерная цель</b><p>{viewed.goal}</p></div></div></section></div></>:<PeopleView key={role} state={state} role={role} onOpenEmployee={id=>{setViewEmployee(id);window.scrollTo(0,0);}} onExport={exportPeople}/>):<>
   {page==='tree'&&<><PageHeading title="Ваше дерево возможностей" mobile="Моё дерево роста" subtitle={`${employee.name.split(' ')[0]} · ${employee.role} · ${employee.grade}`}/><div className="month-row"><div className="month-band"><Icon name="calendar-days" size={25}/><b>{monthName(state.month)}</b><i/><span className={`quota-badge ${attempt?'used':''}`}>{attempt?'Тест месяца пройден':'Доступен 1 тест'}</span><small>Любой тест · одна попытка на месяц</small></div><div className="growth-note"><Icon name="sprout" size={28}/><p>Небольшие шаги сегодня<br/>вырастают в большие возможности завтра.</p></div></div><div className="employee-grid"><div className="tree-column">{treeFor(employee)}<button className="advisor-banner" onClick={()=>navigate('advisor')}><Icon name="sparkles" size={28}/><span><b>Ваш следующий шаг — уже понятен</b><small>Советник подскажет, что развивать и почему.</small></span><Icon name="chevron-right"/></button></div><Catalog employee={employee} attempt={attempt} onTest={openTest} onAll={()=>navigate('catalog')} compact/></div></>}
   {page==='catalog'&&<><PageHeading eyebrow="УЧИТЬСЯ · ПРОБОВАТЬ · РАСТИ" title="Куда вы хотите расти?" subtitle="Навыки вашей профессии — в начале. Любое другое направление тоже открыто."/><div className="catalog-quota"><Icon name="calendar-days"/><span>{monthName(state.month)} · {attempt?'Попытка использована. Обучение остаётся доступным.':'Один тест на выбор. Просматривать каталог можно без ограничений.'}</span></div><Catalog employee={employee} attempt={attempt} onTest={openTest}/></>}
   {page==='results'&&<><PageHeading eyebrow="МОЙ ПРОГРЕСС" title="Каждый навык — с подтверждением" subtitle="Результаты тестов, даты и понятные основания роста."/><div className="summary-cards"><Summary label="Подтверждённых навыков" value={employee.skills.length}/><Summary label="Результатов в истории" value={employee.history.length}/><Summary label="Тест этого месяца" value={attempt?`${attempt.score} / 100`:'Впереди'}/></div><section className="panel results-panel"><h2>История оценок</h2><History employee={employee} onOpen={result=>setModal({kind:'result',result})}/></section><button className="btn btn-primary" onClick={()=>navigate('catalog')}>Выбрать следующий навык<Icon name="arrow-right" size={18}/></button></>}
   {page==='advisor'&&<Advisor employee={employee} attempt={attempt} onTest={openTest} onPlan={test=>setModal({kind:'learning',test})} onMeet={()=>navigate('meetings')}/>}
   {page==='meetings'&&<><PageHeading eyebrow="РАЗВИТИЕ В ДИАЛОГЕ" title="Встречи, которые двигают вперёд" subtitle="Обсудите сильные стороны и следующий шаг с руководителем."/><div className="meet-layout"><section className="panel"><div className="section-heading"><h2>Мои встречи</h2><button className="btn btn-primary" onClick={()=>setModal({kind:'meeting'})}><Icon name="calendar-check" size={18}/>Запланировать</button></div>{state.meetings.filter(m=>m.employeeId===employee.id).length?state.meetings.filter(m=>m.employeeId===employee.id).map(m=><article className="meeting-item" key={m.id}><div className="round-icon"><Icon name="calendar-days"/></div><div><h3>{m.topic}</h3><p>{dateLabel(m.date)} · {m.time} · Айгерим</p><span className="tag">Личный план · приглашение не отправлено</span></div><button className="icon-button" aria-label={`Удалить встречу: ${m.topic}`} onClick={()=>{setState(s=>({...s,meetings:s.meetings.filter(x=>x.id!==m.id)}));setToast('Встреча удалена из личного плана');}}><Icon name="x" size={18}/></button></article>):<div className="empty-state"><Icon name="calendar-days" size={44}/><h3>Время для разговора о вашем росте</h3><p>Выберите тему и дату. В демо встреча сохраняется в личном плане.</p></div>}</section><aside className="panel tinted"><p className="eyebrow">ПОДГОТОВКА К 1:1</p><h2>Начните с сильных сторон</h2><p>У вас {employee.skills.length} подтверждённых навыков. Обсудите, где применить их в реальном проекте.</p><button className="text-button" onClick={()=>navigate('results')}>Посмотреть мои результаты<Icon name="arrow-right" size={18}/></button></aside></div></>}
   {page==='points'&&<><PageHeading eyebrow="РАСТИТЕ В СВОЁМ ТЕМПЕ" title="Маленькие победы. Большое дерево." subtitle="Очки развития отражают подтверждённые навыки и не связаны с банковскими бонусами или ОТК."/><div className="points-hero"><Icon name="award" size={70}/><div><p>Ваши очки развития</p><strong>{employee.skills.length*100}<small> XP</small></strong><span>100 XP за каждый уникальный подтверждённый навык</span></div></div><div className="achievement-grid">{[{name:'Первые корни',need:1,icon:'sprout',text:'Подтвердить первый навык'},{name:'Сильная ветвь',need:3,icon:'git-branch',text:'Подтвердить 3 навыка'},{name:'Широкая крона',need:6,icon:'leaf',text:'Подтвердить 6 навыков'}].map(a=><button className={`achievement ${employee.skills.length>=a.need?'earned':''}`} key={a.name} onClick={()=>setModal({kind:'achievement',achievement:a})}><Icon name={a.icon} size={42}/><h2>{a.name}</h2><p>{a.text}</p><span className="tag">{employee.skills.length>=a.need?'Получено':`${employee.skills.length} из ${a.need}`}</span></button>)}</div></>}
   {page==='profile'&&<><PageHeading title="Мой профиль" subtitle="Ваши навыки сегодня. Ваши возможности завтра."/><div className="profile-shortcuts">{[["results","chart-no-axes-combined","Мои результаты"],["points","award","Мои достижения"],["meetings","calendar-check","Встречи и ревью"]].map(([id,icon,label])=><button className="btn btn-secondary" key={id} onClick={()=>navigate(id)}><Icon name={icon} size={18}/>{label}</button>)}</div><div className="profile-layout"><section className="panel"><span className="avatar large-avatar">{employee.initials}</span><h2>{employee.name}</h2><p>{employee.role} · {employee.grade}</p><dl><dt>Подразделение</dt><dd>{employee.department}</dd><dt>Опыт в компании</dt><dd>{employee.tenure}</dd><dt>Руководитель</dt><dd>Айгерим Садыкова</dd></dl><label className="field-label">Моя карьерная цель<select value={employee.goal} onChange={e=>{const goal=e.target.value;setState(s=>({...s,employees:s.employees.map(p=>p.id===employee.id?{...p,goal}:p)}));setToast('Карьерная цель сохранена');}}>{[...new Set([employee.goal,'Senior Backend Engineer','Data Analyst','Product Manager','Team Lead'])].map(g=><option key={g}>{g}</option>)}</select></label><p className="muted small">Цель помогает выбрать обучение. Повышение обсуждается отдельно.</p></section><section className="panel tinted"><h2>Ваши данные под контролем</h2><p>Результаты видят сотрудник, его руководитель и HR.</p><div className="info-note"><Icon name="lock-keyhole"/><p>Это локальное демо на синтетических профилях. Переключатель ролей показывает интерфейсы и не заменяет авторизацию.</p></div><label className="field-label">Посмотреть другую роль<select value={role} onChange={e=>changeRole(e.target.value)}><option value="employee">Сотрудник</option><option value="manager">Руководитель</option><option value="hr">HR · Полный доступ</option></select></label><button className="btn btn-secondary" onClick={()=>setModal({kind:'settings'})}><Icon name="settings-2" size={18}/>Настройки демо</button></section></div></>}
  </>}
  <footer className="app-footer"><span>Career Quest · пространство вашего роста</span><button onClick={()=>setModal({kind:'methodology'})}>Как работает дерево<Icon name="arrow-right" size={14}/></button></footer></main>
  <nav className="mobile-nav" aria-label="Мобильная навигация">{[['tree','sprout','Путь'],['catalog','target','Тесты'],['advisor','lightbulb','Советник'],['profile','user-round','Профиль']].map(([id,icon,label])=><button className={page===id?'active':''} key={id} onClick={()=>{if(role!=='employee')changeRole('employee');navigate(id);}}><Icon name={icon} size={24}/><span>{label}</span></button>)}<button onClick={()=>setModal({kind:'halyk'})}><b className="halyk-nav-icon">H</b><span>Halyk</span></button></nav>
  {assessment&&<Assessment key={assessment.id} test={assessment} onSubmit={submit} onClose={()=>setAssessment(null)}/>}
  {modal&&<Modal title={modalTitle(modal)} onClose={()=>setModal(null)} wide={modal.kind==='result'||modal.kind==='skills'}>
   {modal.kind==='export'&&<><p>CSV подготовлен по текущей выборке: {modal.count} сотрудников.</p><label className="field-label">Данные CSV<textarea readOnly value={modal.content} rows={7} onFocus={e=>e.target.select()}/></label><div className="button-row"><button className="btn btn-primary" onClick={async()=>{try{await navigator.clipboard.writeText(modal.content);setToast('CSV скопирован');}catch{setToast('Выделите текст CSV и скопируйте его вручную');}}}><Icon name="check-check" size={18}/>Скопировать CSV</button><button className="btn btn-secondary" onClick={()=>{const url=URL.createObjectURL(new Blob([modal.content],{type:'text/csv;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download=`career-quest-${state.month}.csv`;link.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}}><Icon name="download" size={18}/>Скачать файл</button></div><p className="muted small">Если встроенный браузер не сохраняет файл, скопируйте CSV и вставьте его в Excel или текстовый файл.</p></>}
   {modal.kind==='skill'&&<SkillDetail skill={modal.skill} employee={modal.employee} onTest={()=>{setModal(null);openTest(TESTS.find(t=>t.skillId===modal.skill.id));}} canTest={role==='employee'}/>}
   {modal.kind==='skills'&&<><p className="muted">{modal.employee.name} · {modal.employee.skills.length} подтверждённых навыков</p><div className="skills-list">{modal.employee.skills.map(s=><button key={s.id} onClick={()=>setModal({kind:'skill',skill:s,employee:modal.employee})}><Icon name={categoryIcon[s.category]}/><span><b>{s.title}</b><small>{levelName(s.level)} · {dateLabel(s.date)}</small></span><strong>{s.score}<small>/100</small></strong><Icon name="chevron-right" size={17}/></button>)}</div></>}
   {modal.kind==='result'&&<Result result={modal.result} isNew={modal.newResult} onTree={()=>{setModal(null);setPage('tree');setTreeRevision(n=>n+1);window.scrollTo(0,0);}} onAdvisor={()=>{setModal(null);setPage('advisor');}}/>}
   {modal.kind==='quota'&&<><div className="modal-symbol"><Icon name="calendar-check" size={36}/></div><h3>Попытка за {monthName(state.month).toLowerCase()} уже использована</h3><p>Результат: {attempt?.title} · {attempt?.score} / 100. Следующий тест откроется в новом календарном месяце.</p><p className="muted">Пока можно изучать материалы и готовиться к следующему шагу.</p><button className="btn btn-primary" onClick={()=>navigate('advisor')}>Перейти к плану развития<Icon name="arrow-right" size={18}/></button></>}
   {modal.kind==='learning'&&<Learning test={modal.test} initialChecked={state.learning?.[modal.test.id]||[]} onReady={checked=>{setState(s=>({...s,learning:{...s.learning,[modal.test.id]:checked}}));setToast('План подготовки сохранён');setModal(null);}}/>}
   {modal.kind==='meeting'&&<MeetingForm month={state.month} onSave={values=>{setState(s=>({...s,meetings:[...s.meetings,{...values,id:crypto.randomUUID(),employeeId:employee.id}]}));setModal(null);setToast('Встреча добавлена в личный план');}}/>}
   {modal.kind==='settings'&&<><p>Сценарий работает на синтетических данных. Прогресс хранится в этом браузере.</p><label className="field-label">Режим просмотра<select value={role} onChange={e=>changeRole(e.target.value)}><option value="employee">Сотрудник</option><option value="manager">Руководитель · команда Айгерим</option><option value="hr">HR · вся компания</option></select></label><div className="info-note"><Icon name="calendar-days"/><div><b>{monthName(state.month)}</b><p>Можно перейти к следующему месяцу. История сохранится, появится новая попытка.</p></div></div><button className="btn btn-primary" onClick={()=>{setState(nextMonth(state));setModal(null);setToast('Новый месяц — новая возможность роста');}}>Начать следующий месяц<Icon name="arrow-right" size={18}/></button><button className="btn btn-secondary" onClick={()=>setModal({kind:'reset'})}><Icon name="rotate-ccw" size={18}/>Сбросить демо</button></>}
   {modal.kind==='reset'&&<><p>Удалить результаты, личные встречи и выбранную цель из этого демо? Исходные примеры навыков останутся.</p><div className="button-row"><button className="btn btn-secondary" onClick={()=>setModal({kind:'settings'})}>Отмена</button><button className="btn btn-primary" onClick={()=>{setState(initialState());setFreshSkill(null);setModal(null);setPage('tree');setViewEmployee(null);setToast('Демо восстановлено');}}>Да, сбросить</button></div></>}
   {modal.kind==='halyk'&&<div className="superapp-demo"><span className="brand-mark">H</span><p className="eyebrow">ВОЗВРАТ В HALYK</p><h3>Ваш рост — часть большой экосистемы</h3><p>В супераппе эта кнопка закрывает Career Quest и возвращает на главный экран Halyk.</p><div className="info-note">Это автономный прототип. Соединение с Halyk SuperApp ещё не подключено.</div><button className="btn btn-primary" onClick={()=>setModal(null)}>Продолжить в Career Quest</button></div>}
   {modal.kind==='methodology'&&<><p className="modal-lead">Каждая ветвь — подтверждённый навык.</p><ol className="methodology"><li><b>Выберите один тест на месяц.</b><p>Must-have помогает ориентироваться в профессии, но не блокирует другие направления.</p></li><li><b>Ответьте на 5 вопросов.</b><p>В демо {PASS_SCORE} баллов из 100 подтверждают навык. Отправленный тест использует попытку, даже если порог не достигнут.</p></li><li><b>Увидьте свой рост.</b><p>Новый навык добавляет ветвь. Повторное подтверждение обновляет существующий навык, без дополнительных XP.</p></li><li><b>Обсудите следующий шаг.</b><p>Результат виден руководителю и HR. Он не заменяет практическую оценку, ОТК и решение о повышении.</p></li></ol><p className="muted small">Вопросы, порог и профили — демонстрационные. Модель оценки требует согласования с банком. Уровень сложности теста и результат /100 — разные показатели.</p></>}
   {modal.kind==='achievement'&&<div className="achievement-detail"><Icon name={modal.achievement.icon} size={70}/><h3>{modal.achievement.name}</h3><p>{modal.achievement.text}</p><p>{employee.skills.length>=modal.achievement.need?'Достижение уже в вашей коллекции.':`Осталось подтвердить ${modal.achievement.need-employee.skills.length} навыков.`}</p><button className="btn btn-primary" onClick={()=>navigate('catalog')}>Открыть каталог</button></div>}
  </Modal>}
  {toast&&<div className="toast" role="status"><Icon name="circle-check" size={20}/>{toast}</div>}
 </div>;
}

function PageHeading({title,subtitle,mobile,eyebrow}){return <div className="page-heading">{eyebrow&&<p className="eyebrow">{eyebrow}</p>}<h1><span className={mobile?'desktop-title':''}>{title}</span>{mobile&&<span className="mobile-title">{mobile}</span>}</h1>{subtitle&&<p>{subtitle}</p>}</div>;}
function Summary({label,value}){return <div className="summary-card"><small>{label}</small><strong>{value}</strong></div>;}
function recommendation(employee){const target=employee.goal.includes('Data')?'sql':employee.goal.includes('Product')?'product-discovery':employee.goal.includes('Lead')?'leadership':'system-design';return TESTS.find(t=>t.id===target);}
function Catalog({employee,attempt,onTest,onAll,compact=false}){
 const [query,setQuery]=useState(''),[category,setCategory]=useState('all');const match=t=>(!query||`${t.title} ${t.description} ${categoryLabel(t.category)}`.toLowerCase().includes(query.toLowerCase()))&&(category==='all'||t.category===category);const must=getMustHaveTests(employee).filter(match),recommend=recommendation(employee);const count=TESTS.filter(match).length;const otherTests=TESTS.filter(t=>match(t)&&!must.some(m=>m.id===t.id)&&(!match(recommend)||t.id!==recommend.id));
 return <section className={`catalog-panel ${compact?'compact-catalog':'full-catalog'}`} aria-label="Каталог тестов"><div className="catalog-heading"><h2>{compact?'Выберите тест месяца':'Каталог тестов'}</h2><span className="tag">{TESTS.length} тестов · демо</span></div><label className="search-field"><Icon name="search" size={19}/><span className="sr-only">Найти навык или направление</span><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Навык или направление"/></label>{!compact&&<div className="filter-chips" aria-label="Направления"><button className={category==='all'?'selected':''} onClick={()=>setCategory('all')}>Все направления</button>{CATEGORIES.map(c=><button className={category===c.id?'selected':''} key={c.id} onClick={()=>setCategory(c.id)}>{c.label}</button>)}</div>}
  {must.length>0&&<div className="catalog-group"><h3>MUST-HAVE <span>Для вашей профессии</span></h3><p className="group-subtitle">{employee.role} · {employee.grade}</p>{must.map(t=><TestRow key={t.id} test={t} employee={employee} onTest={onTest}/>)}</div>}
  {match(recommend)&&<div className="catalog-group recommended-group"><h3>Для цели {employee.goal.replace(' Backend Engineer','')}</h3><div className="recommended-card"><div className="recommended-info"><span className="recommended-icon"><Icon name="layers" size={27}/></span><div><strong>{recommend.title}</strong><p>{recommend.description}</p></div><span className="tag gold-tag">{levelName(recommend.level)}</span></div><div className="test-meta"><Icon name="clock-3" size={15}/>{recommend.duration} мин <span>·</span> 5 вопросов <span>·</span> Демо</div><button className="btn btn-primary" onClick={()=>onTest(recommend)}>{attempt?'Посмотреть доступность':'Выбрать тест месяца'}<Icon name="arrow-right" size={17}/></button></div></div>}
  <div className="catalog-group all-directions"><h3>{query?'Результаты поиска':'Любое направление'}</h3>{CATEGORIES.filter(c=>otherTests.some(t=>t.category===c.id)).map(c=><details key={`${c.id}-${query}-${category}`} open={Boolean(query)||!compact||c.id==='data'}><summary><Icon name={categoryIcon[c.id]} size={21}/>{c.label}<Icon name="chevron-down" size={17}/></summary><div className="category-tests">{otherTests.filter(t=>t.category===c.id).map(t=><TestRow key={t.id} test={t} employee={employee} onTest={onTest}/>)}</div></details>)}</div>
  {!count&&<div className="empty-state"><Icon name="search" size={30}/><p>Такого теста пока нет в каталоге.</p><button className="text-button" onClick={()=>{setQuery('');setCategory('all');}}>Сбросить поиск</button></div>}{compact&&<button className="catalog-all text-button" onClick={onAll}>Все категории и тесты<Icon name="arrow-right" size={18}/></button>}<div className="privacy-note"><Icon name="lock-keyhole" size={22}/><p>Результат увидят вы, HR и ваш руководитель.<small>Демо-тесты и оценки не являются официальной политикой банка.</small></p></div></section>;
}
function TestRow({test,employee,onTest}){const done=employee.skills.find(s=>s.id===test.skillId);return <button className="test-row" onClick={()=>onTest(test)} aria-label={`Открыть тест ${test.title}`}><span className={`test-row-icon ${test.id==='python'?'python-icon':''}`}><Icon name={test.id==='python'?'code-xml':categoryIcon[test.category]} size={23}/></span><span className="test-row-name"><b>{test.title}</b>{done&&<small><Icon name="check" size={12}/>{done.score} / 100 · подтверждён</small>}</span><span className="level-tag">{levelName(test.level)}</span><span className="test-duration"><Icon name="clock-3" size={15}/>{test.duration} мин</span><Icon name="arrow-right" className="row-arrow" size={17}/></button>;}
function History({employee,onOpen}){return <div className="history-list">{employee.history.map(h=><button className="history-item" onClick={()=>onOpen(h)} key={h.id}><span className={`round-icon ${h.passed?'':'warm'}`}><Icon name={h.passed?'shield-check':'target'}/></span><span><b>{h.title}</b><small>{dateLabel(h.submittedAt)} · {h.passed?'Навык подтверждён':'Есть куда расти'}</small></span><strong>{h.score}<small>/ 100</small></strong><Icon name="chevron-right" size={17}/></button>)}</div>;}
function SkillDetail({skill,employee,onTest,canTest}){return <><div className="skill-detail-head"><span className="round-icon"><Icon name={categoryIcon[skill.category]} size={32}/></span><span><h3>{skill.title}</h3><p>{categoryLabel(skill.category)} · {levelName(skill.level)}</p></span><strong>{skill.score}<small>/100</small></strong></div><div className="info-note"><Icon name="shield-check"/><p>Навык подтверждён · {dateLabel(skill.date)}<br/>{employee.name}</p></div><p>Эта ветвь уже часть вашего дерева. Повторное подтверждение обновит её, без дублирования навыка.</p><p className="muted small">Показан лучший подтверждённый результат. Все попытки доступны в истории оценок.</p>{canTest&&<button className="btn btn-primary" onClick={onTest}>Открыть тест для повторной оценки<Icon name="arrow-right" size={18}/></button>}</>;}
function Result({result,isNew,onTree,onAdvisor}){const test=TESTS.find(t=>t.id===result.testId);return <><div className={`result-hero ${result.passed?'':'result-warm'}`}><div className="result-emblem"><Icon name={result.passed?'sprout':'target'} size={46}/></div><p className="eyebrow">{result.title}</p><h3>{result.passed?(isNew?'Ваше дерево стало сильнее':'Навык подтверждён'):'Первый шаг уже сделан'}</h3><div className="result-number">{result.score}<small>/ 100</small></div><p>{result.passed?'Результат подтверждает навык в демонстрационной модели.':`Для подтверждения нужно ${PASS_SCORE} / 100. Используйте разбор, чтобы подготовиться.`}</p></div>{isNew&&<div className="info-note"><Icon name="calendar-check"/><p>Попытка за {monthName(result.month).toLowerCase()} использована. Результат уже появился у HR и руководителя.</p></div>}{result.answers&&<details className="answer-review"><summary>Разбор ответов<Icon name="chevron-down" size={18}/></summary>{test.questions.map((q,i)=><div className="answer-item" key={q.id}><Icon name={result.answers[i]===q.correct?'circle-check':'circle-x'} size={20}/><div><b>{i+1}. {q.prompt}</b><p>Ваш ответ: {q.options[result.answers[i]]}</p><small>{q.explanation}</small></div></div>)}</details>}<div className="button-row"><button className="btn btn-primary" onClick={onTree}>{isNew&&result.passed?'Посмотреть новую ветвь':'К дереву'}<Icon name="sprout" size={18}/></button>{isNew&&<button className="btn btn-secondary" onClick={onAdvisor}>Мой следующий шаг</button>}</div><p className="muted small">{dateLabel(result.submittedAt)} · Демонстрационная оценка. Не является решением о повышении.</p></>;}
function Advisor({employee,attempt,onTest,onPlan,onMeet}){const rec=recommendation(employee),missing=getMustHaveTests(employee).filter(t=>!employee.skills.some(s=>s.id===t.skillId));return <><PageHeading eyebrow="ВАШ СОВЕТНИК ПО РАЗВИТИЮ" title="Рост начинается с понятного шага" subtitle="Рекомендации на основе вашей цели и подтверждённых навыков."/><div className="advisor-layout"><section className="advisor-hero panel"><Icon name="sparkles" size={36}/><span className="tag">Демо · рекомендации по правилам</span><h2>{employee.name.split(' ')[0]}, у вас уже есть сильная основа.</h2><p>{employee.skills.length} подтверждённых навыков. Ваша цель — <b>{employee.goal}</b>. {employee.skills.some(s=>s.id===rec.skillId)?'Целевой навык уже подтверждён. Следующий шаг — применение на практике и обсуждение с руководителем.':`Рекомендую ${rec.title}: это направление связано с выбранной целью.`}</p><div className="reason-box"><b>Почему этот шаг</b><p>Основание: цель «{employee.goal}», наличие навыков в вашем профиле и список must-have для профессии.</p></div><div className="button-row"><button className="btn btn-primary" onClick={()=>onPlan(rec)}>Открыть план подготовки<Icon name="arrow-right" size={17}/></button><button className="btn btn-secondary" onClick={onMeet}>Обсудить на 1:1</button></div></section><section className="panel"><p className="eyebrow">БЛИЖАЙШИЕ ВОЗМОЖНОСТИ</p><h2>В вашем темпе</h2>{[rec,...missing.filter(t=>t.id!==rec.id)].slice(0,3).map((t,i)=><article className="advisor-step" key={t.id}><span>{i+1}</span><div><h3>{t.title}</h3><p>{t.description}</p><button className="text-button" onClick={()=>attempt?onPlan(t):onTest(t)}>{attempt?'Подготовиться':'Открыть тест'}<Icon name="arrow-right" size={16}/></button></div></article>)}<p className="muted small">Советник не использует LLM в этой версии. Рекомендации объяснимы и воспроизводимы.</p></section></div></>;}
function Learning({test,initialChecked=[],onReady}){const [checked,setChecked]=useState(initialChecked);return <><p className="modal-lead">{test.title} · подготовка без ограничения попыток</p><p className="muted">Учебный план по темам демо-теста. Это не каталог внутренних курсов Halyk.</p>{test.questions.map((q,i)=><label className="learning-step" key={q.id}><input type="checkbox" checked={checked.includes(i)} onChange={()=>setChecked(c=>c.includes(i)?c.filter(n=>n!==i):[...c,i])}/><span><b>Шаг {i+1}</b>{q.explanation}</span></label>)}<div className="progress-track"><span style={{width:`${checked.length/test.questions.length*100}%`}}/></div><p className="muted small">Изучено {checked.length} из {test.questions.length} тем. Этот чек-лист не подтверждает навык.</p><button className="btn btn-primary" onClick={()=>onReady(checked)}>Сохранить план</button></>;}
function MeetingForm({month,onSave}){const [topic,setTopic]=useState('Мой следующий карьерный шаг'),[date,setDate]=useState(`${month}-15`),[time,setTime]=useState('11:00');return <form onSubmit={e=>{e.preventDefault();onSave({topic:topic.trim(),date,time});}}><label className="field-label">Тема встречи<input required maxLength={120} value={topic} onChange={e=>setTopic(e.target.value)}/></label><div className="form-row"><label className="field-label">Дата<input required type="date" min={`${month}-01`} value={date} onChange={e=>setDate(e.target.value)}/></label><label className="field-label">Время<input required type="time" value={time} onChange={e=>setTime(e.target.value)}/></label></div><p className="info-note">Встреча сохранится в личном плане. Приглашение руководителю не отправляется.</p><button className="btn btn-primary" disabled={!topic.trim()} type="submit">Сохранить встречу<Icon name="calendar-check" size={18}/></button></form>;}
function modalTitle(m){return ({export:'Экспорт сотрудников',skill:'Подтверждённый навык',skills:'Мои подтверждённые навыки',result:'Результат теста',quota:'Одна возможность каждый месяц',learning:'План подготовки',meeting:'Новая встреча',settings:'Настройки демонстрации',reset:'Сбросить прогресс?',halyk:'Halyk SuperApp',methodology:'Как работает дерево',achievement:'Моё достижение'})[m.kind]||'Career Quest';}
function Modal({title,onClose,children,wide}){const ref=useRef(null),close=useRef(onClose);close.current=onClose;useEffect(()=>{const previous=document.activeElement,scroll=document.body.style.overflow;document.body.style.overflow='hidden';ref.current?.querySelector('button')?.focus();const listener=e=>{if(e.key==='Escape'){close.current();return;}if(e.key==='Tab'){const items=[...ref.current.querySelectorAll('button:not([disabled]),input,select,textarea,summary,a[href]')].filter(el=>el.offsetParent!==null);const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',listener);return()=>{document.body.style.overflow=scroll;document.removeEventListener('keydown',listener);previous?.focus();};},[]);return <div className="modal-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><section className={`modal ${wide?'modal-wide':''}`} ref={ref} role="dialog" aria-modal="true" aria-labelledby="modal-title"><header><h2 id="modal-title">{title}</h2><button className="icon-button" onClick={onClose} aria-label="Закрыть окно"><Icon name="x"/></button></header><div className="modal-body">{children}</div></section></div>;}
